openapi: "3.0.3"
info:
  title: "TvHistoryApi"
  description: "Управление каналами и списком телепередачь"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"

paths:
  /api/channels:
    get:
      description: "Получить список каналов"
      parameters:
        - name: "limit"
          required: false
          in: "query"

        - name: "offset"
          required: false
          in: "query"

        - name: "playlist-limit"
          required: false
          in: "query"
      responses:
        "200":
          description: "OK"
          content:
            text/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: integer
                    example: 123
                  name:
                    type: string
                    example: "Первый канал"
                  image:
                    type: string
                    example: "https:..."
                  playlist:
                    type: array
                    example: [
                        {
                          id: 123,
                          name: "Они сражались за Родину",
                          timestart: 1719059700,
                          timestop: 1719068400
                        }
                      ]


components:
  schemas: { }